version: '3'

services:
  api:
    build:
      context: ./src/api
      dockerfile: dockerfile
    volumes: 
      - ./src/api:/usr/src/app
    ports:
      - 8001:80
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  app:
    build:
      context: ./src/app
      dockerfile: dockerfile
    volumes:
      - ./src/app:/usr/src/app
    ports:
      - 3001:3000
    depends_on: 
      - api