version: '3.7'

services:
  extractor-service:
    container_name: extractor
    build:
      context: ./src/service-extractor
      dockerfile: dockerfile.prod
    ports:
      - "8989:8989"
    depends_on:
      - db-service
      - firefox
      - chrome
      - hub
    networks: 
      - spiderweb

  job-service:
    container_name: job_service
    build:
      context: ./src/service-job-controller
      dockerfile: dockerfile.prod
    ports:
      - "3777:3777"
    depends_on:
      - extractor-service
    networks: 
      - spiderweb

  db-service:
    container_name: db_api
    build:
      context: ./src/service-db
      dockerfile: dockerfile.dev
    ports:
      - "9000:9000"
    links:
      - mongo
    networks: 
      - spiderweb
      - mongo-internal

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mongo-internal
      
  web-app:
    container_name: web_app
    build:
      context: ./src/app-web
      dockerfile: dockerfile.prod
    ports:
      - "80:80"
    depends_on: 
      - db-service
    networks:
      - spiderweb

  firefox:
    container_name: firefox_driver
    image: selenium/node-firefox:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    networks:
      - hub-internal

  chrome:
    container_name: chrome_driver
    image: selenium/node-chrome:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    networks:
      - hub-internal

  hub:
    container_name: selenium_hub
    image: selenium/hub:3.14.0-gallium
    ports:
      - "4444:4444"
    networks:
      - spiderweb
      - hub-internal

networks: 
  spiderweb:
    driver: bridge
  hub-internal:
    driver: bridge
  mongo-internal:
    driver: bridge
