version: '3'

services:

  extractor-service:
    container_name: extractor
    build:
      context: ./src/service-extractor
      dockerfile: dockerfile
    volumes:
      - ./src/service-extractor:/usr/src/app
    ports:
      - 9001:80
    depends_on:
      - db-service
      - firefox
      - chrome
      - hub

  job-controller-service:
    container_name: job_controller
    build:
      context: ./src/service-job-controller
      dockerfile: dockerfile
    volumes:
      - ./src/service-job-controller/:/usr/src/app
    ports:
      - 5001:5000
    depends_on:
      - extractor-service

  db-service:
    container_name: db_api
    build:
      context: ./src/service-db
      dockerfile: dockerfile
    volumes: 
      - ./src/service-db:/usr/src/app
    ports:
      - 8001:80
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
      
  app:
    container_name: react_app
    build:
      context: ./src/app
      dockerfile: dockerfile
    volumes:
      - ./src/app:/usr/src/app
    ports:
      - 3001:3000
    depends_on: 
      - db-service

  firefox:
    container_name: firefox_driver
    image: selenium/node-firefox:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    container_name: chrome_driver
    image: selenium/node-chrome:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    container_name: selenium_hub
    image: selenium/hub:3.14.0-gallium
    ports:
      - "4444:4444"