version: '3.7'

services:
  extractor-service:
    container_name: extractor
    build:
      context: ./src/service-extractor
      dockerfile: dockerfile
    volumes:
      - ./src/service-extractor:/usr/src/app
    ports:
      - 9001:80
    depends_on:
      - db-service
      - firefox
      - chrome
      - hub
    networks: 
      - spiderweb

  job-controller-service:
    container_name: job_controller
    build:
      context: ./src/service-job-controller
      dockerfile: dockerfile
    volumes:
      - ./src/service-job-controller/:/usr/src/app
    ports:
      - 3778:3777
    depends_on:
      - extractor-service
    networks: 
      - spiderweb

  db-service:
    container_name: db_api
    build:
      context: ./src/service-db
      dockerfile: dockerfile
    volumes: 
      - ./src/service-db:/usr/src/app
    ports:
      - 8001:80
    links:
      - mongo
    networks: 
      - spiderweb
      - mongo-internal

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - mongo-internal
      
  app:
    container_name: react_app
    build:
      context: ./src/app
      dockerfile: dockerfile
    volumes:
      - ./src/app:/usr/src/app
    ports:
      - 3001:3000
    depends_on: 
      - db-service
    networks:
      - spiderweb

  firefox:
    container_name: firefox_driver
    image: selenium/node-firefox:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    networks:
      - hub-internal

  chrome:
    container_name: chrome_driver
    image: selenium/node-chrome:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    networks:
      - hub-internal

  hub:
    container_name: selenium_hub
    image: selenium/hub:3.14.0-gallium
    ports:
      - "4444:4444"
    networks:
      - spiderweb
      - hub-internal

networks: 
  spiderweb:
    driver: bridge
  hub-internal:
    driver: bridge
  mongo-internal:
    driver: bridge