version: '3'

services:

  db-service:
    container_name: db_api
    build:
      context: ./src/service-db
      dockerfile: dockerfile
    volumes: 
      - ./src/service-db:/usr/src/app
    ports:
      - 8001:80
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
      
  app:
    container_name: react_app
    build:
      context: ./src/app
      dockerfile: dockerfile
    volumes:
      - ./src/app:/usr/src/app
    ports:
      - 3001:3000
    depends_on: 
      - db-service