tv_series:
  - "Chernobyl"
  - "Game of Thrones"
  - "Friends"
  - "How to Sell Drugs Online (Fast)"
  - "The Office"
  - "The Simpsons"
headless: false
debug: true
pickle:
  should_pickle: false
  pickle_filename: "outfile"